CREATE EXTENSION IF NOT EXISTS citext;
CREATE TABLE IF NOT EXISTS users(
	id SERIAL,
	username CITEXT UNIQUE,
	password VARCHAR(76),
	email VARCHAR(50),
	sign_up_date TIMESTAMP WITH TIME ZONE,
	roles TEXT[],
	last_online TIMESTAMP WITH TIME ZONE,
	status VARCHAR(25),
	invisible BOOLEAN
);